name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees:
  - koncord

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Are you using this in Browser or Node.js?
      options:
        - Browser
        - Node.js
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Code Sample
      description: Provide a minimal code sample that reproduces the issue
      placeholder: |
        ```typescript
        // Your code here
        ```
      render: typescript
    validations:
      required: false

  - type: input
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      placeholder: e.g., @bis-toolkit/paa, @bis-toolkit/p3d
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: false
